Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,17 +1,20 @@
-name: Lighthouse
-on: push # For every push, this action will be triggered
+name: Build project and Run Lighthouse CI
+on: [push]
 jobs:
-  lighthouse:
-    runs-on: ubuntu-latest #OS
+  lhci:
+    name: Lighthouse CI
+    runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v1
-      - name: Audit URLs using Lighthouse
-        uses: treosh/lighthouse-ci-action@v2
+      - name: Use Node.js 10.x
+        uses: actions/setup-node@v1
         with:
-          urls:
-            https://nadace-neziskovky.now.sh/
-      - name: Save results
-        uses: actions/upload-artifact@v1
-        with:
-          name: lighthouse-results
-          path: '.lighthouseci' # This will save the Lighthouse results as .json files
+          node-version: 10.x
+      - name: npm install, build
+        run: |
+          npm install
+          npm run build
+      - name: run Lighthouse CI
+        run: |
+          npm install -g @lhci/cli@0.3.x
+          lhci autorun --upload.target=temporary-public-storage || echo "LHCI failed!"
